# This file should contain a token to a discord bot.
# A token is like a password, and this is what enables the connection
# of the machine to the bot discord account.
# For obvious reasons, the bot token should not be shared.

# PASTE YOUR DISCORD BOT TOKEN BELOW:
